modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory (36 is current forge version)

license="MIT"

[[mods]] #mandatory

modId="blocksnstuff" #mandatory

version="0.1.0" #mandatory

displayName="Blocks 'N' Stuff" #mandatory

updateJSONURL="" # blank for now!

logoFile="examplemod.png" #optional

authors="caittatic, and cy4 in teacherly spirit" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
caittastic following a tutorial made by Tutorials by Kaupenjoe
thank you to everyone helping me learn java and fix all my confusing issues
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.blocksnstuff]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.blocksnstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,)"
    ordering="NONE"
    side="BOTH"